### ISSUE TITLE
手机端传json文件无反应，只能一个个加？希望修复一下

### ISSUE THREAD

**Issue by bsgn2023** [qallen028/eternity#1]

**Comment by qallen028** [comment]
修改了一個新的版本，更新試一下，我的手機測試是可以的，因爲安卓的版本太多了，所以有可能有兼容問題

**Comment by bsgn2023** [comment]
是的，手机只能导手机，电脑zy的文件无法导手机。我做了一个对比，电脑版zy的json多了一个ID，而缺少method，format，searchable。相对来说手机版的更全，只要把手机版的忽略掉ID就能导入了

**Comment by qallen028** [comment]
其實是可以導入電腦版的，如你說的，導入電腦會缺失method，format，searchable參數，ID其實不是必要的，不能導入可能是key相同，無論手機或電腦key必須是唯一值
